# Keys
title = "Archivo de configuración"

# Tables
[project]
name = "TSP"
description = ""
version = "0.1"
updated = 2020-10-13
author = "Adolfo De Unánue"

[database]
host = "127.0.0.1"
password = "some_password"
port = 5444
name = "my_database"
connection_max = 5000
enabled = true

# Nested `tables`
[environments]
  [environments.dev]
    ip = "10.0.0.1"
    dc = "eqdc10"
  [environments.staging]
    ip = "10.0.0.2"
    dc = "eqdc10"
  [environments.production]
    ip = "10.0.0.3"
    dc = "eqdc10"

# Array of Tables
[[testers]]
id = 1
username = "JohnCena"
password = "YouCantSeeMe69"

[[testers]]
id = 3
username = "TheRock"
password = "CantCook123"
